import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { toast } from "sonner";
import { BarChart3, CalendarDays, ChevronDown, CircleArrowDown, CircleArrowUp, LayoutDashboard, LogOut, Plus, ReceiptText, Sparkles, Trash2, Wallet, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type FormState = { id?: number; type: "income" | "expense"; description: string; amount: string; category: string; occurredAt: string };
const monthNames = ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"];
const defaultYears = Array.from({ length: 11 }, (_, index) => new Date().getFullYear() - index);
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

function initialForm(type: "income" | "expense" = "income"): FormState { return { type, description: "", amount: "", category: "", occurredAt: new Date().toISOString().slice(0, 10) }; }

export default function Home() {
  const { user, loading, logout } = useAuth();
  const [location, setLocation] = useLocation();
  const now = new Date();
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [year, setYear] = useState(now.getFullYear());
  const [form, setForm] = useState<FormState | null>(null);
  const isTransactions = location === "/lancamentos";
  const query = trpc.finance.list.useQuery({ month, year }, { enabled: Boolean(user) });
  const utils = trpc.useUtils();
  const create = trpc.finance.create.useMutation({ onSuccess: () => { utils.finance.list.invalidate(); setForm(null); toast.success("Lançamento adicionado"); } });
  const update = trpc.finance.update.useMutation({ onSuccess: () => { utils.finance.list.invalidate(); setForm(null); toast.success("Lançamento atualizado"); } });
  const remove = trpc.finance.remove.useMutation({ onSuccess: () => { utils.finance.list.invalidate(); toast.success("Lançamento excluído"); } });
  const transactions = query.data ?? [];
  const summary = useMemo(() => transactions.reduce((acc, item) => { const value = Number(item.amount); item.type === "income" ? acc.income += value : acc.expense += value; return acc; }, { income: 0, expense: 0 }), [transactions]);
  const yearOptions = useMemo(() => Array.from(new Set([...defaultYears, ...transactions.map(item => new Date(item.occurredAt).getFullYear())])).sort((a, b) => b - a), [transactions]);
  const chartData = useMemo(() => { const buckets = new Map<number, { month: string; income: number; expense: number }>(); for (const item of transactions) { const m = new Date(item.occurredAt).getMonth(); const current = buckets.get(m) ?? { month: monthNames[m], income: 0, expense: 0 }; current[item.type] += Number(item.amount); buckets.set(m, current); } return Array.from(buckets.values()).sort((a, b) => monthNames.indexOf(a.month) - monthNames.indexOf(b.month)); }, [transactions]);

  if (loading) return <div className="min-h-screen grid place-items-center"><div className="animate-pulse text-muted-foreground">Carregando seu espaço financeiro...</div></div>;
  if (!user) return <Landing onLogin={startLogin} />;

  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form) return; const payload = { ...form, amount: Number(form.amount), occurredAt: new Date(`${form.occurredAt}T12:00:00`) }; if (!payload.description || !payload.category || !payload.amount) { toast.error("Preencha todos os campos"); return; } if (form.id) update.mutate({ ...payload, id: form.id }); else create.mutate(payload); };
  const grouped = { income: transactions.filter(t => t.type === "income"), expense: transactions.filter(t => t.type === "expense") };

  return <div className="min-h-screen bg-[#0b0d12] text-foreground">
    <aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-white/8 bg-[#10131b] px-5 py-6 lg:flex lg:flex-col">
      <div className="flex items-center gap-3 px-2"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-lg shadow-primary/20"><Sparkles className="h-5 w-5" /></div><div><p className="font-semibold tracking-tight">Findash LVO</p><p className="text-xs text-muted-foreground">Seu dinheiro, claro.</p></div></div>
      <nav className="mt-12 space-y-2"><NavItem icon={LayoutDashboard} label="Visão geral" active={!isTransactions} onClick={() => setLocation("/")} /><NavItem icon={ReceiptText} label="Lançamentos" active={isTransactions} onClick={() => setLocation("/lancamentos")} /></nav>
      <div className="mt-auto rounded-2xl border border-white/8 bg-white/[0.03] p-3"><div className="flex items-center gap-3"><Avatar className="h-9 w-9"><AvatarImage src={(user as any).avatarUrl ?? undefined} /><AvatarFallback>{user.name?.slice(0, 1).toUpperCase() ?? "U"}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate text-sm font-medium">{user.name ?? "Usuário"}</p><p className="truncate text-xs text-muted-foreground">{user.email}</p></div></div><Button variant="ghost" size="sm" className="mt-3 w-full justify-start text-muted-foreground" onClick={logout}><LogOut className="mr-2 h-4 w-4" /> Sair</Button></div>
    </aside>
    <main className="lg:pl-64"><header className="sticky top-0 z-20 border-b border-white/8 bg-[#0b0d12]/85 px-4 py-4 backdrop-blur-xl sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-primary">{isTransactions ? "Controle" : "Resumo financeiro"}</p><h1 className="mt-1 text-xl font-semibold tracking-tight sm:text-2xl">{isTransactions ? "Seus lançamentos" : `Olá, ${user.name?.split(" ")[0] ?? "bem-vindo"}.`}</h1></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-xl border border-white/8 bg-white/[0.03] px-3 py-2 sm:flex"><CalendarDays className="h-4 w-4 text-muted-foreground" /><select className="bg-transparent text-sm outline-none" value={month} onChange={e => setMonth(Number(e.target.value))}>{monthNames.map((m, i) => <option className="bg-[#10131b]" key={m} value={i + 1}>{m}</option>)}</select><select className="bg-transparent text-sm outline-none" value={year} onChange={e => setYear(Number(e.target.value))}>{yearOptions.map(option => <option className="bg-[#10131b]" key={option} value={option}>{option}</option>)}</select></div><Button size="icon" className="rounded-xl" onClick={() => setForm(initialForm())}><Plus className="h-5 w-5" /></Button></div></div></header>
      <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8"><div className="flex gap-2 overflow-x-auto pb-1 sm:hidden"><Button variant={!isTransactions ? "secondary" : "ghost"} onClick={() => setLocation("/")}><LayoutDashboard className="mr-2 h-4 w-4" />Resumo</Button><Button variant={isTransactions ? "secondary" : "ghost"} onClick={() => setLocation("/lancamentos")}><ReceiptText className="mr-2 h-4 w-4" />Lançamentos</Button></div><div className="flex items-center gap-2 rounded-2xl border border-white/8 bg-white/[0.03] p-3 sm:hidden"><CalendarDays className="h-4 w-4 text-muted-foreground" /><select className="flex-1 bg-transparent text-sm outline-none" value={month} onChange={e => setMonth(Number(e.target.value))}>{monthNames.map((m, i) => <option className="bg-[#10131b]" key={m} value={i + 1}>{m}</option>)}</select><span className="text-muted-foreground">/</span><select className="bg-transparent text-sm outline-none" value={year} onChange={e => setYear(Number(e.target.value))}>{yearOptions.map(option => <option className="bg-[#10131b]" key={option} value={option}>{option}</option>)}</select></div>{isTransactions ? <TransactionsPage grouped={grouped} onEdit={(item: any) => setForm({ id: item.id, type: item.type, description: item.description, amount: String(item.amount), category: item.category, occurredAt: new Date(item.occurredAt).toISOString().slice(0, 10) })} onDelete={(id: number) => remove.mutate({ id })} /> : <Dashboard summary={summary} chartData={chartData} transactions={transactions} onAdd={() => setForm(initialForm())} />}</div>
    </main>
    {form && <TransactionModal form={form} setForm={setForm} onSubmit={submit} saving={create.isPending || update.isPending} onClose={() => setForm(null)} />}
  </div>;
}

function NavItem({ icon: Icon, label, active, onClick }: { icon: any; label: string; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm transition-colors ${active ? "bg-primary/12 text-primary" : "text-muted-foreground hover:bg-white/5 hover:text-foreground"}`}><Icon className="h-4 w-4" />{label}</button>; }
function Landing({ onLogin }: { onLogin: () => void }) { return <div className="grid min-h-screen place-items-center bg-[#0b0d12] p-6"><div className="w-full max-w-md text-center"><div className="mx-auto mb-6 grid h-16 w-16 place-items-center rounded-3xl bg-primary text-primary-foreground shadow-2xl shadow-primary/25"><Wallet className="h-8 w-8" /></div><p className="mb-3 text-sm font-medium uppercase tracking-[0.25em] text-primary">Findash LVO</p><h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">Finanças sem ruído.</h1><p className="mx-auto mt-5 max-w-sm text-muted-foreground">Organize entradas, saídas e decisões em um painel simples, visual e feito para você.</p><Button onClick={onLogin} size="lg" className="mt-8 h-12 w-full rounded-xl">Entrar com Google</Button><p className="mt-4 text-xs text-muted-foreground">A autenticação segura carrega seu perfil automaticamente.</p></div></div>; }
function Dashboard({ summary, chartData, transactions, onAdd }: any) { return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Saldo no período" value={money.format(summary.income - summary.expense)} icon={Wallet} accent="text-primary" /><Metric title="Entradas" value={money.format(summary.income)} icon={CircleArrowUp} accent="text-emerald-400" /><Metric title="Saídas" value={money.format(summary.expense)} icon={CircleArrowDown} accent="text-rose-400" /><Metric title="Lançamentos" value={String(transactions.length)} icon={BarChart3} accent="text-amber-300" /></div><div className="grid gap-6 xl:grid-cols-[1.4fr_0.6fr]"><section className="rounded-3xl border border-white/8 bg-[#10131b] p-5 sm:p-6"><div className="mb-5 flex items-start justify-between"><div><h2 className="font-semibold">Evolução mensal</h2><p className="mt-1 text-sm text-muted-foreground">Comparativo entre receitas e despesas.</p></div><BarChart3 className="h-5 w-5 text-primary" /></div><div className="h-64">{chartData.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} barGap={8}><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#8a91a4", fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#8a91a4", fontSize: 12 }} tickFormatter={v => `R$${v / 1000}k`} /><Tooltip contentStyle={{ background: "#161a24", border: "1px solid rgba(255,255,255,.1)", borderRadius: 12 }} formatter={(v: number) => money.format(v)} /><Bar dataKey="income" name="Entradas" fill="#7c6cf2" radius={[6, 6, 0, 0]} /><Bar dataKey="expense" name="Saídas" fill="#f36b86" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer> : <EmptyState text="Adicione lançamentos para visualizar sua evolução." onClick={onAdd} />}</div></section><section className="rounded-3xl border border-white/8 bg-[#10131b] p-5 sm:p-6"><h2 className="font-semibold">Últimos lançamentos</h2><div className="mt-4 space-y-3">{transactions.slice(0, 5).map((t: any) => <TransactionRow key={t.id} item={t} />)}{!transactions.length && <p className="py-8 text-center text-sm text-muted-foreground">Nenhum lançamento neste período.</p>}</div></section></div></>; }
function Metric({ title, value, icon: Icon, accent }: any) { return <div className="rounded-3xl border border-white/8 bg-[#10131b] p-5"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{title}</p><Icon className={`h-5 w-5 ${accent}`} /></div><p className="mt-5 text-2xl font-semibold tracking-tight">{value}</p></div>; }
function TransactionsPage({ grouped, onEdit, onDelete }: any) { return <div className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-semibold">Entradas e saídas</h2><p className="mt-1 text-sm text-muted-foreground">Gerencie cada movimento do seu mês.</p></div><p className="text-sm text-muted-foreground">{grouped.income.length + grouped.expense.length} registros</p></div><div className="grid gap-6 xl:grid-cols-2"><TransactionColumn title="Entradas" subtitle="Receitas, salários e ganhos" items={grouped.income} tone="income" onEdit={onEdit} onDelete={onDelete} /><TransactionColumn title="Saídas" subtitle="Despesas e compromissos" items={grouped.expense} tone="expense" onEdit={onEdit} onDelete={onDelete} /></div></div>; }
function TransactionColumn({ title, subtitle, items, tone, onEdit, onDelete }: any) { return <section className="rounded-3xl border border-white/8 bg-[#10131b] p-5 sm:p-6"><div className="flex items-center gap-3"><div className={`grid h-10 w-10 place-items-center rounded-2xl ${tone === "income" ? "bg-emerald-400/12 text-emerald-400" : "bg-rose-400/12 text-rose-400"}`}>{tone === "income" ? <CircleArrowUp className="h-5 w-5" /> : <CircleArrowDown className="h-5 w-5" />}</div><div><h3 className="font-semibold">{title}</h3><p className="text-xs text-muted-foreground">{subtitle}</p></div></div><div className="mt-5 space-y-2">{items.length ? items.map((item: any) => <TransactionRow key={item.id} item={item} actions onEdit={onEdit} onDelete={onDelete} />) : <p className="rounded-2xl border border-dashed border-white/10 py-10 text-center text-sm text-muted-foreground">Nenhum registro aqui.</p>}</div></section>; }
function TransactionRow({ item, actions, onEdit, onDelete }: any) { return <div className="group flex items-center gap-3 rounded-2xl px-3 py-3 transition-colors hover:bg-white/[0.04]"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${item.type === "income" ? "bg-emerald-400/10 text-emerald-400" : "bg-rose-400/10 text-rose-400"}`}>{item.type === "income" ? <CircleArrowUp className="h-4 w-4" /> : <CircleArrowDown className="h-4 w-4" />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.description}</p><p className="text-xs text-muted-foreground">{item.category} · {new Date(item.occurredAt).toLocaleDateString("pt-BR")}</p></div><p className={`text-sm font-semibold ${item.type === "income" ? "text-emerald-400" : "text-rose-400"}`}>{item.type === "income" ? "+" : "−"}{money.format(Number(item.amount))}</p>{actions && <div className="hidden gap-1 group-hover:flex"><Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => onEdit(item)}><ChevronDown className="h-4 w-4 rotate-[-90deg]" /></Button><Button variant="ghost" size="icon" className="h-8 w-8 text-rose-400" onClick={() => onDelete(item.id)}><Trash2 className="h-4 w-4" /></Button></div>}</div>; }
function EmptyState({ text, onClick }: any) { return <div className="grid h-full place-items-center rounded-2xl border border-dashed border-white/10 p-6 text-center"><div><p className="text-sm text-muted-foreground">{text}</p><Button variant="secondary" className="mt-4" onClick={onClick}><Plus className="mr-2 h-4 w-4" />Adicionar lançamento</Button></div></div>; }
function TransactionModal({ form, setForm, onSubmit, saving, onClose }: any) { return <div className="fixed inset-0 z-50 grid place-items-end bg-black/70 p-0 backdrop-blur-sm sm:place-items-center sm:p-4"><div className="w-full max-w-lg rounded-t-3xl border border-white/10 bg-[#141822] p-5 shadow-2xl sm:rounded-3xl sm:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-primary">Novo movimento</p><h2 className="mt-1 text-xl font-semibold">{form.id ? "Editar lançamento" : "Adicionar lançamento"}</h2></div><Button variant="ghost" size="icon" onClick={onClose}><X className="h-5 w-5" /></Button></div><form onSubmit={onSubmit} className="space-y-4"><div className="grid grid-cols-2 gap-2">{(["income", "expense"] as const).map(type => <button type="button" key={type} onClick={() => setForm({ ...form, type })} className={`rounded-xl border px-3 py-3 text-sm font-medium ${form.type === type ? (type === "income" ? "border-emerald-400/40 bg-emerald-400/10 text-emerald-400" : "border-rose-400/40 bg-rose-400/10 text-rose-400") : "border-white/10 text-muted-foreground"}`}>{type === "income" ? "Entrada" : "Saída"}</button>)}</div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label>Descrição</Label><Input value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Ex.: Salário, aluguel..." /></div><div className="space-y-2"><Label>Valor</Label><Input type="number" min="0" step="0.01" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} placeholder="0,00" /></div><div className="space-y-2"><Label>Categoria</Label><Input value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} placeholder="Ex.: Moradia" /></div><div className="space-y-2 sm:col-span-2"><Label>Data</Label><Input type="date" value={form.occurredAt} onChange={e => setForm({ ...form, occurredAt: e.target.value })} /></div></div><Button type="submit" disabled={saving} className="h-11 w-full rounded-xl">{saving ? "Salvando..." : form.id ? "Salvar alterações" : "Adicionar lançamento"}</Button></form></div></div>; }
